### ISSUE TITLE
Semantic Relation Classification via Bidirectional LSTM Networks with Entity-aware Attention using Latent Entity Typing  no paper

### ISSUE THREAD

**Issue by zhoudayang** [roomylee/awesome-relation-extraction#3]
Semantic Relation Classification via Bidirectional LSTM Networks with Entity-aware Attention using Latent Entity Typing

**Comment by roomylee** [comment]
add link of the paper. thank you.

* Semantic Relation Classification via Bidirectional LSTM Networks with Entity-aware Attention using Latent Entity Typing [[paper]](https://arxiv.org/abs/1901.08163)
	* Joohong Lee, Sangwoo Seo and Yong Suk Choi
	* arXiv 2019
